"""create weather records table

Revision ID: 3d66ee3edbda
Revises: ccece848c1d3
Create Date: 2026-05-14 08:30:47.455182

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d66ee3edbda'
down_revision: Union[str, Sequence[str], None] = 'ccece848c1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_query', sa.String(), nullable=False),
    sa.Column('resolved_location', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('weather_main', sa.String(), nullable=True),
    sa.Column('weather_description', sa.String(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f("ix_weather_records_id"),
        "weather_records",
        ["id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_records_id'), table_name='weather_records')
    op.drop_table('weather_records')
    # ### end Alembic commands ###
