"""add search history table

Revision ID: fa512ae2a7aa
Revises: 3d66ee3edbda
Create Date: 2026-05-15 08:23:45.170525

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa512ae2a7aa"
down_revision: Union[str, Sequence[str], None] = "3d66ee3edbda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("weather_record_id", sa.Integer(), nullable=True),
        sa.Column("query", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["weather_record_id"],
            ["weather_records.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_search_history_id"),
        "search_history",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_search_history_user_id"),
        "search_history",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_search_history_user_id"),
        table_name="search_history",
    )

    op.drop_index(
        op.f("ix_search_history_id"),
        table_name="search_history",
    )

    op.drop_table("search_history")
    # ### end Alembic commands ###